name: Build Installer Wizard Plugin

on:
  push:
    branches: master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/run-vcpkg@v11

      - name: Configure Installer Wizard Plugin build
        shell: pwsh
        run: |
          cmake --preset vs2022-windows "-DCMAKE_INSTALL_PREFIX=install"

      - name: Build Installer Wizard Plugin
        run: cmake --build vsbuild --config RelWithDebInfo

      - name: Install Installer Wizard Plugin
        run: cmake --install vsbuild --config RelWithDebInfo

      - name: Upload Installer Wizard Plugin artifact
        uses: actions/upload-artifact@master
        with:
          name: installer_wizar
          path: ./install/plugins/installer_wizard
